service: sqsgateway
frameworkVersion: '1'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    SQS_HTTP_URL:
      Ref: AsyncAPIQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:GetQueueUrl"
        - "sqs:SendMessage"
      Resource:
        - 'Fn::GetAtt': [AsyncAPIQueue, Arn]

functions:
  submit:
    handler: handlers/push.get
    timeout: 30
    events:
      - http:
          path: submit
          method: get
          cors: true

resources:
  - ${file(resources/sqs.yml)}
