service: sqsgateway
frameworkVersion: '1'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    SQS_HTTP_URL:
      Ref: AsyncAPIQueue
    API_KEY_ARN:
      Ref: APIKeySecret
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:GetQueueUrl"
        - "sqs:SendMessage"
      Resource:
        - 'Fn::GetAtt': [AsyncAPIQueue, Arn]
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - Ref: APIKeySecret

functions:
  submit:
    handler: handlers/push.post
    timeout: 30
    events:
      - http:
          path: submit
          method: POST
          cors: false

resources:
  - ${file(resources/sqs.yml)}
  - ${file(resources/secrets.yml)}
