service: asyncapi
frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    timeout: 30
    events:
      - http:
          path: hello
          method: get
