Resources:
  APIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: API key used to validate requests
      GenerateSecretString:
        PasswordLength: 18
        ExcludeCharacters: "'"
      Name: ${self:service}-${self:provider.stage}-APIKey
